### ISSUE TITLE
Minor UX: adapt default aliases

### ISSUE THREAD

**Issue by Fuchs** [freenode/kiwiirc#10]
Currently the aliases include modes that are not supported on freenode, like half-op. 
I assume this can be configured per instance and thus a set more usable on freenode should be chosen. 

(Maybe also do remove the /slap one)

**Comment by prawnsalad** [comment]
@tomaw if you want to set custom aliases, you can add `"aliases": "the aliases config text here"` to your config.

Maybe some aliases to common services/channel/access list functions?

**Comment by Fuchs** [comment]
fixed
