### ISSUE TITLE
Minor UX: pre-fill channel or let users connect without

### ISSUE THREAD

**Issue by Fuchs** [freenode/kiwiirc#11]
Currently (at least on Firefox) it's not possible to hit connect when the channel field is empty. Users new to the webchat (I assume it can be embedded with preselected channels, even though the GUI does not seem to offer such an option) might not know what channels are / which ones to join, so maybe a default example could be added?

Also there might be use cases where users do not want to join channels at all.

**Comment by prawnsalad** [comment]
A default channel can be added from the kiwi.freenode.net config. @tomaw is a default channel wanted for freenode? I find it's handy for getting poeple to connect easier if they're not sure how it allw orks, but it does attract more idiots. On kiwi I have #kiwiirc-default setup for this reason.

**Comment by Fuchs** [comment]
from the internal discussion I gather that the old behaviour might be prefered, would it be possible to override that and let people connect to no channels? 

There are use cases where this makes sense  (if you only want to connect to check something or query someone, or if you need to do $things before joining etc.)

**Comment by prawnsalad** [comment]
I've now added a `allowNoChannel` config option to allow this use case
