### ISSUE TITLE
Even though kiwi.freenode.net has connecting to other networks disabled, "Network Settings" still has options for it (but they don't work)

### ISSUE THREAD

**Issue by fndax** [freenode/kiwiirc#2]
Steps to reproduce:

1. Click freenode on the left-hand menu
2. Click Settings on the top tab list
3. Note all of this stuff that shouldn't be here (maybe one or two things should, but most of it is useless and confusing):

![image](https://user-images.githubusercontent.com/23448388/41258465-0ecf88ee-6d85-11e8-868d-65c51de04e9e.png)

4. Click "Remove Network" because lol why not
5. Get sent back to login screen
6. Note that logging in doesn't work any more, clicking Start doesn't do anything

**Comment by meldra** [comment]
note that the settings are also offered on the disconnect screen per #4

**Comment by prawnsalad** [comment]
I've got these hidden in restricted mode now. via https://github.com/kiwiirc/kiwiirc/commit/d4961b5bdf7013eb21d85dedddb3573ae6f2d088 and https://github.com/kiwiirc/kiwiirc/commit/fc0c8390c1eb01bb60499fc0079801ead07da6ad

**Comment by fndax** [comment]
Fixed on kiwi.freenode.net.
