### ISSUE TITLE
Scrolling the User Info pane doesn't work

### ISSUE THREAD

**Issue by fndax** [freenode/kiwiirc#3]
Scrolling the user info pane (the one that pops up when you click a nick in the channel member list) doesn't work, there's no scrollbar:

![image](https://user-images.githubusercontent.com/23448388/41258612-a78378e8-6d85-11e8-9d83-7d620879b0dd.png)

**Comment by prawnsalad** [comment]
Fixed in https://github.com/kiwiirc/kiwiirc/commit/08c32b5027e66030f61340a900f88551d708a4ec

**Comment by fndax** [comment]
Fixed on kiwi.freenode.net.
