### ISSUE TITLE
Reconnect button doesn't result in reconnecting.

### ISSUE THREAD

**Issue by meldra** [freenode/kiwiirc#4]
When disconnected, the following appears:

![image](https://user-images.githubusercontent.com/1224145/41260064-c332b1e4-6d8a-11e8-96c9-d79549b94078.png)

When clicking on the reconnect button it spins stuck:
![image](https://user-images.githubusercontent.com/1224145/41259325-1424bca8-6d88-11e8-9aa7-a01b2b27a74a.png)

Tested on windows chrome and android firefox.

Not urgent as webchat doesn't have a reconnect function at all, but it is full of lies.

**Comment by prawnsalad** [comment]
hey @meldra, do any messages appear in the server tab when you try reconnecting?

**Comment by meldra** [comment]
this is probably related somehow:

![image](https://user-images.githubusercontent.com/1224145/41259932-48685734-6d8a-11e8-8bb1-93e93f29ddbc.png)

the captcha box isn't getting fired up (and is probably unnecessary for reconnect) and thus is stalling the reconnect and hanging the user with a red box and spinning arrows.

**Comment by prawnsalad** [comment]
Perfect, that's what I'm looking for :)

**Comment by meldra** [comment]
this seems to be working fine now.
