### ISSUE TITLE
Outgoing PRIVMSG without spaces with leading : have the : stripped

### ISSUE THREAD

**Issue by fndax** [freenode/kiwiirc#6]
Sending the message `:test` actually sends the message `test`. Sending the message `::test` actually sends the message `:test`. Sending the message `:test test` works correctly.

Notably, there's a button to send a :D emoticon, which actually sends just D if you have it on a line by itself (which is how I noticed this in the first place).

**Comment by prawnsalad** [comment]
I nor others can reproduce this. What browser version + OS are you trying this on?

**Comment by fndax** [comment]
Happens in Firefox 60 on Windows and Linux, on kiwi.freenode.net

**Comment by tomaw** [comment]
Replicated and fixed by upgrading the gateway
