### ISSUE TITLE
/away is in the autocomplete command list but I can't get it to do anything

### ISSUE THREAD

**Issue by fndax** [freenode/kiwiirc#8]
Tried `/away` and `/away test`, not seeing an away message when I `/whois` from another connection either way.

**Comment by prawnsalad** [comment]
kiwiuser types `/away sss`
irssi user runs `/whois kiwiuser` and sees `away     : sss`
kiwiuser types `/away`
irssi user runs `whois kiwiusers` and does not see any away message

I can't reproduce. Am I missing something?

**Comment by fndax** [comment]
Nope, turns out I am actually an idiot and my client puts away messages from users I have a PM window open with, in the PM window. Closing issue.
